name: build-appimagetool

on:
  workflow_dispatch:
    inputs:
      tag-or-ref:
        description: ビルドするappimagetoolのタグまたはコミットハッシュ

jobs:
  build-appimagetool:
    strategy:
      matrix:
        include:
        - arch: x86_64
          os: ubuntu-latest
        - arch: aarch64
          os: ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout appimagetool
        uses: actions/checkout@v5
        with:
          repository: AppImage/appimagetool
          ref: ${{ inputs.tag-or-ref }}
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build appimagetool
        run: |
          mkdir dist
          cd dist
          ARCH=${{ matrix.arch }} bash ../ci/build-in-docker.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apppimagetool-${{ matrix.arch }}
          path: dist/appimagetool*.AppImage*

  get-build-info:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.info.outputs.tag }}

    steps:
      - name: Checkout appimagetool
        uses: actions/checkout@v5
        with:
          repository: AppImage/appimagetool
          ref: ${{ inputs.tag-or-ref }}

      - name: Get git infomation
        id: info
        run: |
          if git describe --tags --exact-match > dev/null ; then
            echo "tag=$(git describe --tags --exact-match)" >> $GITHUB_OUTPUT
          else
            echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LICENSE
          path: LICENSE

  upload-release:
    runs-on: ubuntu-latest

    needs:
      - build-appimagetool
      - get-build-info

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: apppimagetool-*/appimagetool-*.AppImage,LICENSE/LICENSE
          tag: appimagetool-${{ needs.get-build-info.outputs.tag }}
